django/0923_run/bread_sisters/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
]

django/0923_run/bread_sisters/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
#   - 게시글 작성  ( /create/ )
    path('create/', views.create, name='create'),
#   - 게시글 전체 조회  ( / )
    path('', views.index, name='index'),
#   - 게시글 상세 조회  ( /<int:id>/ )
    path('<int:id>', views.detail, name='detail')
#   - 게시글 수정  ( /<int:id>/update/ )
#   - 게시글 삭제  ( /<int:id>/delete/ )
]

django/0923_run/bread_sisters/bakeries/urls.py
from django.urls import path
from . import views

app_name = 'bakeries'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
    
    
    # 테스트용
    
    path('test/', views.test, name='test'),
]

django/0923_run/bread_sisters/bread_sisters/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bakeries/', include('bakeries.urls')),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

django/0923_run/bread_sisters/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(max_length=100)

django/0923_run/bread_sisters/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

django/0923_run/bread_sisters/bakeries/models.py
from django.db import models

# Create your models here.

class Bakery(models.Model):
    # 빵집 이름 (20자 이내)
    name = models.CharField(max_length=20)

    # 주소
    address = models.TextField()

    # 평점 (예: 0.0 ~ 5.0 범위 예상, 소수점 1자리까지)
    rating = models.FloatField()

    # 시작/종료 시간
    opening_time = models.DateTimeField()
    closing_time = models.DateTimeField()
    
    def __str__(self):
        return f'{self.name} {self.rating}/10'

django/0923_run/bread_sisters/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'nickname')

django/0923_run/bread_sisters/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        labels = {
            'title' : '제목',
            'content' : '내용'        
        }
        fields = "__all__"

django/0923_run/bread_sisters/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import SignupForm


# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('bakeries:index')
    else:
        form = SignupForm()
        
    context = {
        'form' : form,
    }    
    
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('bakeries:index')
    else:
        form = AuthenticationForm
        
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

django/0923_run/bread_sisters/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    response = render(request, 'articles/index.html', context)
    response.set_cookie(
        key='username',
        value='giryun',
    )
    return response

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
        
        
    context = {
        'form' : form,
    }
    return render(request, 'articles/create.html', context)

def detail(request, id):
    article = get_object_or_404(Article, id=id)
    
    context = {
        'article' : article,
    }
    
    return render(request, 'articles/detail.html', context)

django/0923_run/bread_sisters/bakeries/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Bakery
from django.utils import timezone
import random

# Create your views here.
def index(request):
    bakeries = Bakery.objects.all().order_by("-rating")
    for bakery in bakeries:
        print(bakery.name)
        print(bakery.rating)
    
    context = {
        "bakeries" : bakeries,
    }
    return render(request, "bakeries/index.html", context)


def detail(request, id):
    bakery = get_object_or_404(Bakery, id=id)
    
    context = {
        'bakery' : bakery,
    }
    
    return render(request, 'bakeries/detail.html', context)


def create(request):
    if request.method == "POST":
        print(request.POST)
        name = request.POST.get('name')
        address = request.POST.get('address')
        rating = request.POST.get('rating')
        opening_time = request.POST.get('opening_time')
        closing_time = request.POST.get('closing_time')
        
        Bakery.objects.create(
            name=name,
            address=address,
            rating=rating,
            opening_time=opening_time,
            closing_time=closing_time,
        )
        
        return redirect('bakeries:index')
    
    else:
        return render(request, 'bakeries/create.html')
    
    
def delete(request, id):
    bakery = get_object_or_404(Bakery, id=id)
    bakery.delete()
    return redirect("bakeries:index")



def update(request, id):
    bakery = get_object_or_404(Bakery, id=id)
    
    if request.method == 'POST':
        name = request.POST.get('name')
        address = request.POST.get('address')
        rating = request.POST.get('rating')
        opening_time = request.POST.get('opening_time')
        closing_time = request.POST.get('closing_time')
        
        bakery.name = name
        bakery.address = address
        bakery.rating = rating
        bakery.opening_time = opening_time
        bakery.closing_time = closing_time
        bakery.save()
        
        return redirect('bakeries:detail', bakery.id)
    
    else:
        context = {
            'bakery' : bakery
        }
        return render(request, 'bakeries/update.html', context)
    




def test(request):
    Bakery.objects.create(
            name='test',
            address='test',
            rating=round(random.uniform(0.0, 5.0), 1),
            opening_time=timezone.now(),
            closing_time=timezone.now()
        )
        
    return redirect('bakeries:index')

django/0923_run/bread_sisters/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h2>로그인 페이지</h2>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>로그인하기</button>
</form>


{% endblock content %}

django/0923_run/bread_sisters/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h2>회원가입 페이지</h2>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>회원가입하기</button>
</form>


{% endblock content %}

django/0923_run/bread_sisters/articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
    <h1>게시글 생성하기</h1>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>제출하기</button>
    </form>

{% endblock content %}

django/0923_run/bread_sisters/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
    <h1>게시판</h1>

    <button><a href="{% url 'articles:create' %}">생성하기</a></button>

    {% for article in articles %}
        <p>제목: {{ article.title }}</p>
        <p>내용: {{ article.content }}</p>
        <hr>

    {% empty %}
    <p>아직 등록된 게시글이 없습니다.</p>
    {% endfor %}

{% endblock content %}

django/0923_run/bread_sisters/bakeries/templates/bakeries/create.html
{% extends "base.html" %}

{% block content %}
    <h2>생성 페이지</h2>

    <form action="{% url 'bakeries:create' %}" method='POST'>
        {% csrf_token %}
        <p>
            <label for="">이름 : </label>
            <input type="text" id="name" name='name' required>
        </p>

        <p>
            <label for="address">주소 : </label>
            <input type="text" id="address" name='address' required>
        </p>


        <p>
            <label for="rating">평점 : </label>
            <input type="number" step="0.1" id="rating" name='rating' min="0" max="10" required>
        </p>

        <p>
            <label for="opening_time">오픈 시간 : </label>
            <input type="datetime-local" id="opening_time" name='opening_time' required>
        </p>


        <p>
            <label for="closing_time">마감 시간 : </label>
            <input type="datetime-local" id="closing_time" name='closing_time' required>
        </p>

        <button>생성하기</button>

        


    </form>

    
{% endblock content %}

django/0923_run/bread_sisters/bakeries/templates/bakeries/detail.html
{% extends "base.html" %}

{% block content %}
<h2>상세 페이지</h2>

    
    <p>이름 : {{ bakery.name }}</p>
    <p>평점 : {{ bakery.rating }}</p>
    <p>주소 : {{ bakery.address }}</p>
    <p>오픈 시간 : {{ bakery.opening_time|date:"h:i A" }}</p>
    <p>마감 시간 : {{ bakery.closing_time|date:"h:i A" }}</p>

    <hr>

    <form action="{% url 'bakeries:delete' bakery.id %}" method='POST'>
        {% csrf_token %}
        <button>삭제</button>
    </form>
    <a href="{% url 'bakeries:update' bakery.id %}">
    <button>수정</button>
    </a>
{% endblock content %}

django/0923_run/bread_sisters/bakeries/templates/bakeries/index.html
{% extends "base.html" %}

{% block content %}
<h2>메인 페이지</h2>

    <button><a href="{% url 'bakeries:create' %}">생성하기</a></button> |
    <button><a href="{% url 'bakeries:test' %}">더미 데이터 생성</a></button>

    {% for bakery in bakeries %}
    <p>이름 : <a href="{% url 'bakeries:detail' bakery.id %}">{{ bakery.name }}</a></p>
    <p>평점 : {{ bakery.rating }}</p>

    <hr>
    {% endfor %}

{% endblock content %}

django/0923_run/bread_sisters/bakeries/templates/bakeries/update.html
{% extends "base.html" %}

{% block content %}
    <h2>수정 페이지</h2>

    <form action="{% url 'bakeries:update' bakery.id %}" method='POST'>
        {% csrf_token %}
        <p>
            <label for="">이름 : </label>
            <input type="text" id="name" name='name' value='{{ bakery.name }}' required>  
        </p>

        <p>
            <label for="address">주소 : </label>
            <input type="text" id="address" name='address' value='{{ bakery.address }}' required>
        </p>


        <p>
            <label for="rating">평점 : </label>
            <input type="number" step="0.1" id="rating" name='rating' value={{ bakery.rating }} min="0" max="10" required>
        </p>

        <p>
            <label for="opening_time">오픈 시간 : </label>
            <input type="datetime-local" id="opening_time" name='opening_time' value={{ bakery.opening_time|date:'Y-m-d\\TH:i' }} required>
        </p>


        <p>
            <label for="closing_time">마감 시간 : </label>
            <input type="datetime-local" id="closing_time" name='closing_time' value={{ bakery.closing_time|date:'Y-m-d\\TH:i' }} required>
        </p>

        <button>수정하기</button>

        


    </form>

    
{% endblock content %}